### ISSUE TITLE
Gallery snippet not working on mobile

### ISSUE THREAD

**Issue by buddh4** [humhub-contrib/gallery#57] opened 2020-05-21 11:15 UTC
When opening the the mobile sidebar with gallery snippet an error is logged:

```
Uncaught TypeError: Cannot read property 'firstChild' of undefined
    at i.loadElement (blueimp-gallery.js:1098)
    at i.loadElements (blueimp-gallery.js:1127)
    at i.handleSlide (blueimp-gallery.js:971)
    at i.handleSlide (blueimp-gallery-indicator.js:132)
    at i.handleSlide (blueimp-gallery-video.js:43)
    at i.onslide (blueimp-gallery.js:980)
    at i.slide (blueimp-gallery.js:380)
    at blueimp-gallery.js:416
```
![grafik](https://user-images.githubusercontent.com/9800854/82553792-02d90280-9b65-11ea-847a-937c6339719b.png)

**Comment by MasterMindNET** [comment] 2020-06-06 20:03
Hello @buddh4, could you please specify the exact steps(can be a video) to reproduce this error? Are you running the latest versions of the HubHub and Gallery module?

Because if I go to the gallery either from the user's page or space page I do not have this error.

**Comment by MasterMindNET** [comment] 2020-07-09 13:19
Good day, @buddh4!

I have found maybe something helpful, please check it out and please report me back if it helps, or let me know where I can fix this JS file.

[https://github.com/dimsemenov/PhotoSwipe/issues/833](source link)

Thank you!

**Comment by MasterMindNET** [comment] 2020-07-15 15:14
I have tried to updated the blueimp-gallery to v.3.1.1

And I have got this error: `Uncaught TypeError: Cannot read property 'removeAttribute' of undefined` instead of `... firstChild...`
![image](https://user-images.githubusercontent.com/22347676/87562565-d7871580-c6c6-11ea-96ae-ed1e9e5ef23d.png)

does anybody has any thoughts on this topic?

**Comment by luke-** [comment] 2020-07-15 16:00
@MasterMindNET hmm no idea. is this code from blueimp?

**Comment by MasterMindNET** [comment] 2020-07-15 20:57
Yeah, the screenshot code is from the blueimg-gallery lib.
The error appears as on 2.3.6 ver and in the 3.1.1(if I am not mistaken
with the version

**Comment by luke-** [comment] 2020-07-16 09:39
Can we update to a more recent version of blueimp gallery?
Is this a known problem from blueimp?

**Comment by MasterMindNET** [comment] 2020-07-30 15:13
> Can we update to a more recent version of blueimp gallery?
> Is this a known problem from blueimp?

As I have mentioned before, I have tried to update to the other version of the blueprint gallery, but it did not help me. the error was persisting.
if I tried to update it, and I did not run this code:
`grunt -h && grunt clean`
Is it a possible issue or not?

After I updated to the latest version that time, it just changed the message to 
> And I have got this error: `Uncaught TypeError: Cannot read property 'removeAttribute' of undefined` instead of `... firstChild...`
the quoted text above and the image shows the error line. I believe there are some other issues. I have tried to run on the official website, and it works w/o issues there in mobile mode.

Thank you!

**Comment by buddh4** [comment] 2020-07-31 12:08
I think the problem is, the snippet is initialized invisible, and blueimp probably needs to calculate some positions/dimensions etc, which is not possible in this case. Perhaps we could try to reinitialize the gallery on swipe, or just hide it on mobile for now.

**Comment by MasterMindNET** [comment] 2020-08-08 12:07
> I think the problem is, the snippet is initialized invisible, and blueimp probably needs to calculate some positions/dimensions, etc, which is not possible in this case. Perhaps we could try to reinitialize the gallery on swipe, or just hide it on mobile for now. Also, the blueimp gallery is part of the core, so we should be careful when we consider updating.

Yeah, I just tried to check if the update helps with this issue, I would ask you or @luke- for such serious things.


I have found that there is an init part of `static\js\humhub\humhub.ui.gallery.js` and the `blueimp.Gallery($links.get(), options);` which initialize the gallery module AFAIK.
The question is how I can call a function when a user opens the right side-bar in this file `static/js/humhub/humhub.ui.gallery.js`? If I am not mistaken.
Should I somehow detect the opening on my own or there is some module/js_file which can help me with it.

Thank you!

**Comment by yurabakhtin** [comment] 2020-10-27 11:37
@luke- I could reproduce the bug from first comment:

<img width="1808" alt="reproduce_bug" src="https://user-images.githubusercontent.com/6995524/97296495-d044db80-1861-11eb-92d2-ea852911ed56.png">

**Comment by MasterMindNET** [comment] 2020-10-27 13:22
As it was supposed earlier, we need to reinitialize  the gallery snippet when it is hidden(on some tablets, mobile phones)

**Comment by yurabakhtin** [comment] 2020-10-27 13:43
One solution is to add option for `blueimp.Gallery` here https://github.com/humhub-contrib/gallery/blob/master/widgets/views/gallerySnippet.php#L56 like:

```
onslide: function (index, slide) {
   if ($(this.options.container).is(':hidden')) {
       this.pause();
   }
},
```

in this case the slider is stopped on page load when sidebar is hidden because no reason to play it when it is not visible on page.

But this solution has an issue, steps to reproduce:

- load page on ipad portrait size 768x1024,
- no error, because the slider is paused, it is loaded in hidden div `.layout-sidebar-container`,
- rotate ipad to landscape size 1024x768, so sidebar become visible,
- click to run the slider animation,
- rotate back to portrait size 768x1024,
- after some time on slide to next picture you will catch the error on console, because the slider is playing in hidden sidebar.

Probably we should override somehow the method `blueimp.Gallery.loadElement(index)` e.g. on `blueimp.Gallery.onopen()` because there is a code to get property `firstChild` of undefined `this.slides[index]`.

**Comment by luke-** [comment] 2020-10-27 15:04
Thanks, I'm not sure how we should proceed here. 

@buddh4 Can you take a look here which approach would be good?

**Comment by yurabakhtin** [comment] 2020-10-27 15:08
@luke- @buddh4 I implemented a fix to avoid error `firstChild of undefined` by prevent original function when passed `NaN` instead of expected integer on small mobile screens with hidden sidebar. But please note if switch to large screen from small then slider is not playing automatically, it can be start only manually, I think it is enough, if not then I think we can do something fix for this, but indeed this is a bug from blurimp library side and we should not do similar fixes I think.

**Comment by luke-** [comment] 2020-10-27 15:11
@yurabakhtin Awesome, this solution should be sufficient.

**Comment by buddh4** [comment] 2020-10-28 12:38
Shouldn't we at least hide the snippet by css? We should not display an empty/black gallery snippet on mobile.

**Comment by buddh4** [comment] 2020-10-28 12:41
[Here](https://github.com/humhub/humhub/blob/master/static/js/humhub/humhub.ui.view.js#L100) is the sidebar swipe handler, maybe we should trigger an global event once the sidebar was closed/opened?

**Comment by MasterMindNET** [comment] 2020-10-28 16:00
There is definitely some problem with the `humhub-contrib/gallery`. As it is working w/o any problems on the `blueimp-gallery`, As I have created the [mentioned link](https://github.com/humhub-contrib/gallery/issues/57#issuecomment-666443068) earlier and the reply was that there are some problems on our side.
So I believe The first thing we could try is to reinit the gallery when it is opened or try something else.

**Comment by yurabakhtin** [comment] 2020-10-29 05:04
@buddh4 

> Shouldn't we at least hide the snippet by css? We should not display an empty/black gallery snippet on mobile. Maybe we could rerender the gallery snippet once the sidebar was opened?

Please tell me how to make visible the empty/black gallery snippet on mobile, because as you can see on my screenshots above the sidebar is completely hidden with all snippets if screen width less 991px.
And when I switch to large screen I can see the sidebar with properly working gallery snippet without errors.

The sidebar is hidden by css media rule:
<img width="1549" alt="hidden_gallery_snippet" src="https://user-images.githubusercontent.com/6995524/97527767-28dcbb80-19bd-11eb-97b3-9d50bb222c67.png">

**Comment by buddh4** [comment] 2020-10-29 09:58
@yurabakhtin on mobile the sidebar can be opened by left swipe.

**Comment by luke-** [comment] 2020-10-29 10:02
@buddh4 
![image](https://user-images.githubusercontent.com/4736168/97553756-220e7280-19d6-11eb-8af1-82a0fd2ee8ac.png)

Is this option required for this?

Is there any reason why not enable this by default?

**Comment by buddh4** [comment] 2020-10-29 10:13
Not sure, we may wanted to activate this in a following version? Did not even know this is deactivated by default since I can't remember activating it manually in my test environment.

**Comment by luke-** [comment] 2020-10-29 11:29
@buddh4  I never used it, your call :-)

**Comment by yurabakhtin** [comment] 2020-10-29 12:33
@buddh4 

> on mobile the sidebar can be opened by left swipe.

ok, thanks for the info, I didn't know this feature before.

Pleas review my new fix for the issue in commit https://github.com/humhub-contrib/gallery/commit/a73918fd8794b5b65c9e22cfae381cac5fa072fd, this fix stops gallery initialization when it is hidden, because it cannot calculate sizes properly, so I implemented to start the initialization only when gallery is visible.
<img width="1170" alt="fixed_swiped_sidebar_gallery" src="https://user-images.githubusercontent.com/6995524/97573909-81cb4480-19fb-11eb-96b2-2c2d3482ab3b.png">

Please note I kept my previous fix, because sometimes when I switch between landscape and portrait ipad sizes I get the error `firstChild of undefined` without that fix, as I understand sometimes there `NaN` is passed as `index` param.

**Closed** 2020-11-04 09:17 UTC
Labels: bug
