### ISSUE TITLE
Links to comments in Gallery are wrong

### ISSUE THREAD

**Issue by ilsd** [humhub-contrib/gallery#123] opened 2023-05-08 17:44 UTC
If someone comments to a gallery, the resulting link in the daily e-mail summary is wrong. Since also the permalink of that comment is wrong, the latter may be the root-cause.

Link in E-Mail and perma-link (wrong):     
https://forum.gumpi.wien/comment/perma?id=171

Link of the page, where the comment is shown:     
https://forum.gumpi.wien/s/umgestaltung-gumpendorfer-strasse/gallery/custom-gallery?gid=9#.jpeg

HumHub Version: 1.13.1, Gallery 1.4.0
<img width="1015" alt="Bildschirmfoto 2023-05-08 um 08 44 08" src="https://user-images.githubusercontent.com/813670/236893618-1bfe9bc1-84a5-43f9-a50b-8b52eb1291af.png">

**Comment by miqrogroove** [comment] 2024-03-06 13:51
I'm having this problem in HumHub 1.15.3.  In both the emails and in the website notifications, the comment link format is `notification/entry?id=1373&cId=4258` and always forwards to the profile page of the user who created the gallery.  Very awkward.

**Comment by miqrogroove** [comment] 2024-03-06 13:52
Duplicate of #113

**Closed** 2024-03-06 15:14 UTC
Labels: bug
